### ISSUE TITLE
Séparer remises BVC et BVE

### ISSUE THREAD

**Issue by Vayel** [Vayel/GUCEM-BVC#12]
Hériter du modèle `BankDeposit`.

**Comment by Vayel** [comment]
@j-bo y a-t-il des informations propres aux remises BVC ou aux remises BVE ? Pour l'instant, j'ai pour les deux : 

* date
* numéro de remise

**Comment by j-bo** [comment]
Sur une remise BVE il y a l'info de remise en trésorerie, mais qui peut
être stockée ailleurs, c'est juste que c'est bien de l'attacher à la remise.

2016-11-29 10:29 GMT+01:00 Vincent Lefoulon <notifications@github.com>:
