### ISSUE TITLE
Informations bancaires sur les commandes groupées

### ISSUE THREAD

**Issue by Vayel** [Vayel/GUCEM-BVC#19]
Actuellement, le tréso renseigne juste le montant et la date lorqu'une commande groupée est reçue. Devrait-il pouvoir également spécifier une référence au virement (un peu comme pour les remises en banque) ? @j-bo

**Comment by j-bo** [comment]
Pas besoin.

**Comment by j-bo** [comment]
A la rigueur un ID type commande n°N
