### ISSUE TITLE
Un état "A traiter" pour les commandes ?

### ISSUE THREAD

**Issue by Vayel** [Vayel/GUCEM-BVC#2]
Pour l'instant, le premier état d'une commande est _placed_, et le second _prepared_ ou _received_. On n'a donc pas d'état pour dire que la commande a été effectuée par l'adhérent/la commission et validée par le respo mais pas encore envoyée au Vieux. De même, pour les commandes groupées, il n'est actuellement pas possible d'en créer petit à petit.

Autrement dit, il faudrait avoir un bouton pour dire : "commande individuelle validée donc à ajouter à la prochaine commande groupée" puis un autre bouton pour envoyer la commande groupée au tréso.

**Comment by j-bo** [comment]
En fait jusqu'ici ça ne marche pas comme ça. Pour le moment les commandes "vieuxcamp" et "adhérents sont totalement décorrélées. La commande au vieux camp est longue et compliquée au niveau administratif, facture etc, du coup il vaut mieux en faire peu, et des grosses. 

Pour ne pas faire attendre les adhérents trop longtemps on essaie donc d'avoir un stock de bvc en amont des commandes qu'ils vont passer, c'est au respo bvc du juger quand il doit "renflouer" son stock de bvc.

**Comment by Vayel** [comment]
Justement, tu n'en étais pas venu à la conclusion qu'il était préférable de récolter les commandes individuelles en début de mois puis de passer une grosse commande pour satisfaire ces commandes individuelles ?

Après, même en restant sur le système actuel, où une grosse commande est juste là pour renflouer le stock, n'est-il pas intéressant de connaître pour une commande individuelle d'où (de quelle grosse commande) proviennent les bons ?

**Comment by j-bo** [comment]
oui bien vu c'est vrai que j'avais proposé ca j'avais zappé :D Du coup c'est mieux comme tu as fait !!
