### ISSUE TITLE
Gestion du stock de bons

### ISSUE THREAD

**Issue by Vayel** [Vayel/GUCEM-BVC#5]
Garde-t-on une seule ligne dans la table, qu'on met à jour à chaque fois qu'on reçoit une commande groupée (+) et prépare des commandes individuelles (-), ou stocke-t-on chaque opération en fonction du temps ?

**Comment by j-bo** [comment]
Je pense qu'il faut une ligne pour le total "bons en stock" + stockage des opérations ce qui permet de calculer les stocks de bons dans chaque état.

**Comment by Vayel** [comment]
On peut faire une ligne par opération contenant : 
- Type d'opération (ajout via préparation de commande groupée, retrait via distribution de commande)
- Date
- Montant BVC restant après opération

**Comment by j-bo** [comment]
Ou juste avec le montant de l'opération en question ? Le montant restant est calculé automatiquement à partir de l'historique ?

**Comment by Vayel** [comment]
Ca me semble un peu lourd, non ? Ca veut dire qu'au bout d'un an 
d'activité, il faudra parcourir toutes les opérations sur l'année passée 
pour connaître le stock courant.

**Comment by j-bo** [comment]
oui en effet !
