### ISSUE TITLE
Optimiser types de bons

### ISSUE THREAD

**Issue by Vayel** [Vayel/GUCEM-BVC#6]
Préparer des commandes de 500 euros avec des bons de 10, c'est relou. Je me demandais donc si on ne pouvait pas optimiser la commande groupée pour correspondre exactement (ou avec une petite marge d'erreur) aux commandes effectuées.

Par exemple, si je n'ai que trois commandes, toutes de 200 euros, demander au Vieux uniquement des bons de 50 euros.

**Comment by j-bo** [comment]
Pratique pour le respo certes... mais dans la mesure où le vieux ne rend pas la monnaie j'essayais toujours de donner au moins 100€ en bons de 10€.

**Comment by Vayel** [comment]
Ah oui, bien vu.

**Comment by j-bo** [comment]
Après on peut calculer pour optimiser qu'il y ait toujours :
- 10 \* 10€ si commande inférieure à 200€ 
- 10 \* 10€ + 5*20€ si commande supérieure à 250€
  (mais c'est du détail)

**Comment by Vayel** [comment]
Il serait également possible d'ajouter un champ lors de la commande pour connaître le nombre d'achats prévu. Si la personne commande 500 pour acheter un produit à 495 euros, on peut se permettre de lui donner principalement des bons de 50.
