### ISSUE TITLE
Rappeler au trésorier de passer commande

### ISSUE THREAD

**Issue by Vayel** [Vayel/GUCEM-BVC#72]
Ajouter un état "passée au magasin" aux commandes groupées. Tant que la commande est dans l'état "passée au trésorier", envoyer un rappel tous les jours par mail.

**Comment by j-bo** [comment]
Bonne idée !... :)

Le 3 nov. 2017 22:18, "Vincent Lefoulon" <notifications@github.com> a
écrit :

**Comment by Vayel** [comment]
@j-bo la prochaine fois qu'une commande groupée sera passée, il faudra que tu ailles sur le site pour faire changer son état en "Passée au magasin". Pour la prochaine, attends un ou deux jours avant de le faire, pour vérifier que tu reçois bien les mails de rappel (un par jour normalement).
